# level6/antecedent_refiner.py
"""
AntecedentRefiner -- Task 21: Regenerate tighter candidate rules from
predicate_evolver output (antecedent_refinements.json).

The predicate_evolver (Task 20) mines discriminant conditions that reduce the
False Positive Rate of FPR-failing candidate rules.  However, the evolver may
suggest conditions that CONTRADICT the base antecedent.  This module:

  1. Loads antecedent_refinements.json (from Task 20).
  2. For each symbol with can_resolve_with_existing=True:
       a. Parses the existing candidate rule antecedent to build a set of
          positive predicates (P) and negative predicates (N).
       b. For each suggested condition "AND NOT pred":
            - If pred is in P AND mu_tp[pred] > CONTRADICTION_THRESHOLD:
                TRUE CONTRADICTION (adding NOT pred would exclude most TP rows
                because TPs already have pred > threshold).  SKIP.
            - If pred is in P AND mu_tp[pred] <= CONTRADICTION_THRESHOLD:
                VALID TIGHTENING (TPs have low pred, so NOT pred still fires).
                In product t-norm this creates a quadratic peak: the rule fires
                most strongly at moderate pred values.  INCLUDE.
            - If pred not in base antecedent: safe addition.  INCLUDE.
       c. Writes the refined rule JSON to
          level6/data/candidate_rules/R_{sid}_refined.json.
       d. Updates the symbol registry candidate_rule_name.

Contradiction test
------------------
For "AND NOT pred > 0.45" vs base antecedent positive pred:
  mu_tp = mean predicate probability in TP rows.
  If mu_tp > 0.45 (most TPs would fail the NOT condition) => contradiction.
  If mu_tp <= 0.45 (TPs satisfy the NOT condition) => valid tightening.

S_001 analysis
--------------
  Base:    is_sre_domain AND NOT is_incident
  Suggested:
    AND NOT has_runbook > 0.45    : has_runbook not in base => INCLUDE
    AND NOT is_sre_domain > 0.45  : is_sre_domain in positive_predicates,
                                    mu_tp=0.5195 > 0.45 => CONTRADICTION => SKIP
    AND NOT is_infrastructure > 0.45 : not in base => INCLUDE
  Refined: is_sre_domain AND NOT is_incident AND NOT has_runbook AND NOT is_infrastructure
  Semantic: SRE-domain investigate request that is NOT runbook-anchored and NOT infrastructure-only.

S_003 analysis
--------------
  Base:    is_unknown AND NOT is_incident
  Suggested:
    AND NOT is_unknown > 0.45 : is_unknown in positive_predicates,
                                mu_tp=0.2514 <= 0.45 => VALID TIGHTENING => INCLUDE
  In product t-norm: p(is_unknown) x (1-p(is_unknown)) x (1-p(is_incident))
  This peaks at moderate is_unknown (~0.3-0.45), suppressing the high-is_unknown
  (is_unknown=0.87) FP rows while preserving the low-is_unknown (0.25) TP rows.
  Refined: is_unknown AND NOT is_unknown AND NOT is_incident
  Semantic: summarization request that is MODERATELY unknown (not strongly OOF).

Usage
-----
    python -m level6.antecedent_refiner

    python -m level6.antecedent_refiner --symbol S_001 S_003 --dry-run
"""

from __future__ import annotations

import argparse
import copy
import json
import sys
from pathlib import Path
from typing import Optional

REPO_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(REPO_ROOT))

from level6.symbol_registry import SymbolRegistry   # noqa: E402

DEFAULT_REFINEMENTS   = REPO_ROOT / "level6" / "data" / "antecedent_refinements.json"
DEFAULT_CANDIDATE_DIR = REPO_ROOT / "level6" / "data" / "candidate_rules"
DEFAULT_REGISTRY      = REPO_ROOT / "level6" / "data" / "symbol_registry.json"

# Threshold used by predicate_evolver for all "AND NOT pred > threshold" conditions.
CONDITION_THRESHOLD = 0.45

# A suggested "AND NOT pred" is contradictory when the base antecedent requires pred
# AND mu_tp > CONTRADICTION_THRESHOLD (meaning most TP rows would fail the condition).
CONTRADICTION_THRESHOLD = CONDITION_THRESHOLD


# ---------------------------------------------------------------------------
# Antecedent parsing
# ---------------------------------------------------------------------------

def _parse_base_predicates(
    antecedent: dict,
) -> tuple[set[str], set[str]]:
    """
    Walk the antecedent tree and return (positive_predicates, negative_predicates).

    positive_predicates: predicate names that appear without negation.
    negative_predicates: predicate names that appear under a NOT.

    Only handles the AND-of-literals form generated by rule_candidate_gen.py.
    """
    positive: set[str] = set()
    negative: set[str] = set()

    if antecedent.get("logic") == "AND":
        for operand in antecedent.get("operands", []):
            if operand.get("predicate") == "NOT":
                inner = operand.get("operand", {})
                if "predicate" in inner:
                    negative.add(inner["predicate"])
            elif "predicate" in operand:
                positive.add(operand["predicate"])

    return positive, negative


# ---------------------------------------------------------------------------
# Condition parsing
# ---------------------------------------------------------------------------

def _parse_condition(condition_str: str) -> Optional[tuple[str, str]]:
    """
    Parse a condition string from antecedent_refinements.json.

    Supported forms:
      "AND NOT pred > 0.45"  -> ("NOT", "pred")
      "AND pred >= 0.55"     -> ("AND", "pred")

    Returns (condition_type, predicate_name) or None if unparseable.
    """
    s = condition_str.strip()

    if s.startswith("AND NOT "):
        # e.g. "AND NOT has_runbook > 0.45"
        rest = s[len("AND NOT "):].strip()
        pred = rest.split()[0]
        return "NOT", pred

    if s.startswith("AND "):
        # e.g. "AND is_metric >= 0.55"
        rest = s[len("AND "):].strip()
        pred = rest.split()[0]
        return "AND", pred

    return None


# ---------------------------------------------------------------------------
# Contradiction check
# ---------------------------------------------------------------------------

def _check_contradiction(
    cond_type: str,
    predicate: str,
    positive_predicates: set[str],
    negative_predicates: set[str],
    tp_means: dict[str, float],
) -> tuple[bool, str]:
    """
    Check if the suggested condition contradicts the base antecedent.

    Returns (is_contradictory, reason_string).
    """
    mu_tp = tp_means.get(predicate, 0.0)

    if cond_type == "NOT":
        # "AND NOT pred" conflicts with positive pred in base
        if predicate in positive_predicates:
            if mu_tp > CONTRADICTION_THRESHOLD:
                reason = (
                    f"'AND NOT {predicate}' contradicts base '{predicate}': "
                    f"mu_tp={mu_tp:.4f} > {CONTRADICTION_THRESHOLD} -- "
                    f"most TP rows would fail this condition"
                )
                return True, reason
            else:
                # Valid tightening: TPs have low pred, quadratic product t-norm peak
                reason = (
                    f"'AND NOT {predicate}' with base '{predicate}': "
                    f"mu_tp={mu_tp:.4f} <= {CONTRADICTION_THRESHOLD} -- "
                    f"VALID TIGHTENING (quadratic peak in product t-norm)"
                )
                return False, reason
        if predicate in negative_predicates:
            reason = (
                f"'AND NOT {predicate}' is redundant with existing 'NOT {predicate}'"
            )
            return True, reason   # skip redundant duplicate

    elif cond_type == "AND":
        # "AND pred" conflicts with negative pred in base
        if predicate in negative_predicates:
            reason = (
                f"'AND {predicate}' contradicts base 'NOT {predicate}'"
            )
            return True, reason

    return False, "ok"


# ---------------------------------------------------------------------------
# Antecedent builder
# ---------------------------------------------------------------------------

def _build_antecedent_operand(cond_type: str, predicate: str) -> dict:
    """Build an antecedent operand dict from (cond_type, predicate)."""
    if cond_type == "NOT":
        return {"predicate": "NOT", "operand": {"predicate": predicate}}
    else:
        return {"predicate": predicate}


# ---------------------------------------------------------------------------
# Per-symbol refinement
# ---------------------------------------------------------------------------

def refine_symbol(
    refinement: dict,
    candidate_dir: Path,
    dry_run: bool = False,
) -> Optional[dict]:
    """
    Produce a refined candidate rule JSON for one symbol.

    Returns the refined rule dict, or None if refinement is not applicable.
    """
    sid       = refinement["symbol_id"]
    sym_name  = refinement["symbol_name"]
    orig_fpr  = refinement["original_fpr"]
    conditions= refinement["suggested_additional_conditions"]
    tp_means  = refinement["tp_predicate_means"]
    top_discs = {d["predicate"]: d for d in refinement["top_discriminants"]}

    if not refinement.get("can_resolve_with_existing"):
        print(f"  [{sid}] can_resolve_with_existing=False -- no refinement possible")
        return None

    print(f"\n  [{sid}] {sym_name}")
    print(f"      original_fpr : {orig_fpr:.4f}")
    print(f"      estimated_residual_fpr (pre-filter): {refinement['estimated_residual_fpr']:.4f}")

    # Load original candidate rule
    candidate_files = sorted(candidate_dir.glob(f"R_{sid}*.json"))
    # Exclude already-refined files from previous runs
    candidate_files = [f for f in candidate_files if "_refined" not in f.name]
    if not candidate_files:
        print(f"  [{sid}] No candidate rule JSON found in {candidate_dir} -- skipping")
        return None

    with open(candidate_files[0]) as f:
        original_rule = json.load(f)

    # Parse base antecedent
    base_antecedent = original_rule["antecedents"]
    positive_preds, negative_preds = _parse_base_predicates(base_antecedent)
    print(f"      base positive: {sorted(positive_preds)}")
    print(f"      base negative: {sorted(negative_preds)}")

    # Evaluate each suggested condition
    accepted: list[tuple[str, str]] = []   # (cond_type, predicate)
    rejected: list[tuple[str, str, str]] = []   # (cond_type, predicate, reason)

    for cond_str in conditions:
        parsed = _parse_condition(cond_str)
        if parsed is None:
            print(f"      [WARN] Could not parse condition: {cond_str!r} -- skipping")
            continue

        cond_type, predicate = parsed
        contradictory, reason = _check_contradiction(
            cond_type, predicate, positive_preds, negative_preds, tp_means
        )

        if contradictory:
            rejected.append((cond_type, predicate, reason))
            print(f"      [REJECTED] {cond_str}")
            print(f"                 reason: {reason}")
        else:
            accepted.append((cond_type, predicate))
            tag = "VALID TIGHTENING" if "TIGHTENING" in reason else "OK"
            print(f"      [ACCEPTED] {cond_str}  ({tag})")
            if reason != "ok":
                print(f"                 note: {reason}")

    if not accepted:
        print(f"      No valid refinement conditions after filtering -- no change")
        return None

    # Build refined antecedent
    refined_operands = list(base_antecedent.get("operands", []))
    for cond_type, predicate in accepted:
        refined_operands.append(_build_antecedent_operand(cond_type, predicate))

    refined_antecedent = {
        "logic": "AND",
        "operands": refined_operands,
    }

    # Build refined rule
    refined_rule = copy.deepcopy(original_rule)
    refined_rule["antecedents"] = refined_antecedent

    # Update name and description.
    # File is saved as R_{sid}_refined.json; the rule's internal "name" field
    # uses the full descriptive string.  The registry candidate_rule_name is
    # set to the file-stem so the validator can locate the file.
    orig_name    = original_rule["name"]
    refined_name = orig_name + "_refined"
    file_stem    = f"R_{sid}_refined"          # matches the saved filename
    refined_rule["name"]          = refined_name
    refined_rule["_l6_file_stem"] = file_stem     # used by run_refinement to update registry

    added_conds = " ".join(
        f"NOT {p}" if t == "NOT" else p for t, p in accepted
    )
    refined_rule["description"] = (
        original_rule.get("description", "").rstrip(".")
        + f". Antecedent tightened by PredicateEvolver (Task 20/21): "
        + f"added {added_conds}. Contradictory conditions removed: "
        + (", ".join(f"NOT {p}" for _, p, _ in rejected) if rejected else "none")
        + "."
    )

    # L6 traceability
    refined_rule["_l6_refined_from"]              = orig_name
    refined_rule["_l6_rejected_conditions"]       = [reason for _, _, reason in rejected]
    refined_rule["_l6_accepted_conditions"]       = [f"{t} {p}" for t, p in accepted]
    refined_rule["_l6_original_fpr"]             = orig_fpr
    refined_rule["_l6_estimated_residual_fpr"]   = refinement["estimated_residual_fpr"]

    # Human-readable antecedent description
    parts: list[str] = []
    for op in refined_operands:
        if op.get("predicate") == "NOT":
            parts.append(f"NOT {op['operand']['predicate']}")
        else:
            parts.append(op["predicate"])
    antecedent_str = " AND ".join(parts)
    print(f"      refined antecedent: {antecedent_str}")
    print(f"      refined rule name : {refined_name}")

    # Save
    out_path = candidate_dir / f"R_{sid}_refined.json"
    if not dry_run:
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(refined_rule, f, indent=2)
        print(f"      [saved] {out_path}")
    else:
        print(f"      [dry-run] would save to {out_path}")

    return refined_rule


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------

def run_refinement(
    refinements_path: Path,
    candidate_dir: Path,
    registry_path: Path,
    symbol_ids: Optional[list[str]],
    dry_run: bool,
) -> dict[str, dict]:
    """
    Refine all applicable symbols and update the registry.

    Returns {symbol_id: refined_rule_dict} for each successfully refined symbol.
    """
    with open(refinements_path) as f:
        refinements: list[dict] = json.load(f)

    registry = SymbolRegistry(registry_path)

    if symbol_ids:
        refinements = [r for r in refinements if r["symbol_id"] in symbol_ids]

    print(f"[AntecedentRefiner] Processing {len(refinements)} refinement(s) ...")
    results: dict[str, dict] = {}

    for ref in refinements:
        refined = refine_symbol(ref, candidate_dir, dry_run=dry_run)
        if refined is not None:
            sid = ref["symbol_id"]
            results[sid] = refined
            refined_name = refined["name"]
            if not dry_run:
                registry.update_validation(
                    sid,
                    candidate_rule_name=refined.get("_l6_file_stem", refined["name"]),
                    rule_strength_init=refined.get("rule_strength_init"),
                )

    if not dry_run and results:
        registry.save()
        print(f"\n[AntecedentRefiner] Registry updated -> {registry_path}")

    return results


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="AntecedentRefiner -- Task 21: regenerate tighter candidate rules"
    )
    parser.add_argument("--symbol",        nargs="*", default=None,
                        help="Symbol IDs to refine (default: all in refinements file)")
    parser.add_argument("--refinements",   type=Path, default=DEFAULT_REFINEMENTS)
    parser.add_argument("--candidate-dir", type=Path, default=DEFAULT_CANDIDATE_DIR)
    parser.add_argument("--registry",      type=Path, default=DEFAULT_REGISTRY)
    parser.add_argument("--dry-run",       action="store_true",
                        help="Print refinements without writing files")
    args = parser.parse_args()

    results = run_refinement(
        refinements_path = args.refinements,
        candidate_dir    = args.candidate_dir,
        registry_path    = args.registry,
        symbol_ids       = args.symbol,
        dry_run          = args.dry_run,
    )

    print(f"\n{'='*70}")
    print(f"  AntecedentRefiner Summary")
    print(f"{'='*70}")
    print(f"  Refined rules produced : {len(results)}")
    for sid, rule in results.items():
        ops = rule["antecedents"].get("operands", [])
        parts = []
        for op in ops:
            if op.get("predicate") == "NOT":
                parts.append(f"NOT {op['operand']['predicate']}")
            else:
                parts.append(op["predicate"])
        print(f"    [{sid}]  {' AND '.join(parts)}")
    if args.dry_run:
        print("\n  (dry-run -- no files written)")
    print(f"\n  Next: re-run Task 11 validation with refined rules:")
    print(f"    python -m level6.rule_validator")
    print(f"{'='*70}")


if __name__ == "__main__":
    main()
